### ISSUE TITLE
池の数問題 の index化処理について

### ISSUE THREAD

**Issue by dnaga392** [doragon/aribon#1]
対象コミット 9ee58a4 

l.12 で enumerate を使っている for ループですが、この場合 i は [0, len(lakeList)-1] の範囲で順に得られますので、'W' の位置インデックスのリストを取得するのであれば、 l.16-20の処理は不要となるかと思います。

**Comment by doragon** [comment]
@dNaga392 
Wのindex位置だけでなく、左右も池として認識するため、この処理が必要と思われますが、いかがでしょうか？

**Comment by doragon** [comment]
58ce779c6e26a102bef0f63f88c77ab92776fe5a
